name: CI

on:
  push:
    branches: [ "main", "branch_dev_1", "branch_dev_2", "branch_dev_3" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas con Maven
        run: mvn -B test
